//! Rustdoc is generated by AI. System is developed by MincomK.
//!
//! Protofish is an intermediate transport layer that abstracts transportation of streams
//! and messages between various Zako3 components.
//!
//! This crate provides a Rust implementation of the Protofish protocol, which supports:
//! - Arbitrary binary messaging over a connection
//! - Lossy/Lossless binary streaming
//! - Context tracking for request-response patterns
//!
//! # Notes
//! Since `new_arb()` is internally conceptual function, it does not transfer any data itself.
//! So waiting for message after `new_arb` will hang.
//!
//! # Examples
//!
//! ```no_run
//! use std::sync::Arc;
//! use protofish::{connect, accept, UTP, IntegrityType};
//!
//! // Client side
//! async fn client_example<U: UTP>(utp: Arc<U>) {
//!     let conn = connect(utp).await.unwrap();
//!     let arb = conn.new_arb();
//!
//!     let mut stream = arb.new_stream(IntegrityType::Reliable).await.unwrap();
//!     // stream: AsyncReadExt + AsyncWriteExt
//! }
//!
//! // Server side
//! async fn server_example<U: protofish::utp::UTP>(utp: std::sync::Arc<U>) {
//!     let conn = accept(utp).await.unwrap();
//!     let arb = conn.next_arb().await.unwrap();
//!
//!     let mut stream = arb.wait_stream().await.unwrap();
//!     // stream: AsyncReadExt + AsyncWriteExt
//! }
//! ```

mod prost_generated {
    #![allow(warnings)]

    pub mod common {
        pub mod v1 {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/prost_generated/common.v1.rs"
            ));
        }
    }

    pub mod payload {
        pub mod v1 {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/prost_generated/payload.v1.rs"
            ));
        }
    }
}

mod constant;
mod core;
mod error;
mod internal;
pub mod schema;
pub use schema::*;
pub mod utp;

pub use core::client::connect;
pub use core::common::arbitrary::*;
pub use core::common::connection::*;
pub use core::server::accept;
pub use utp::UTP;
