//! Rustdoc is generated by AI. System is developed by MincomK.
//!
//! Protofish is an intermediate transport layer that abstracts transportation of streams
//! and messages between various Zako3 components.
//!
//! This crate provides a Rust implementation of the Protofish protocol, which supports:
//! - Arbitrary binary messaging over a connection
//! - Lossy/Lossless binary streaming
//! - Context tracking for request-response patterns
//!
//! # Examples
//!
//! ```no_run
//! use protofish::{connect, accept};
//!
//! // Client side
//! async fn client_example<U: protofish::utp::UTP>(utp: std::sync::Arc<U>) {
//!     let conn = connect(utp).await.unwrap();
//!     let (writer, reader) = conn.new_arb();
//!     // Send and receive arbitrary data
//! }
//!
//! // Server side
//! async fn server_example<U: protofish::utp::UTP>(utp: std::sync::Arc<U>) {
//!     let conn = accept(utp).await.unwrap();
//!     let ctx = conn.next_arb().await.unwrap();
//!     // Handle incoming context
//! }
//! ```

mod prost_generated {
    #![allow(warnings)]

    pub mod common {
        pub mod v1 {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/prost_generated/common.v1.rs"
            ));
        }
    }

    pub mod payload {
        pub mod v1 {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/prost_generated/payload.v1.rs"
            ));
        }
    }
}

mod constant;
mod core;
mod error;
mod internal;
pub mod schema;
pub use schema::*;
pub mod utp;

pub use core::client::connect;
pub use core::common::arbitrary::*;
pub use core::server::accept;
